# Generated by Django 3.2.7 on 2021-09-22 14:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('macro_api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='food',
            name='meal',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='foods', to='macro_api.meal'),
        ),
        migrations.AlterField(
            model_name='meal',
            name='title',
            field=models.CharField(default='', max_length=255),
        ),
    ]
